### ISSUE TITLE
while running git2consul command, getting "Config value is not valid JSON: undefined"

### ISSUE THREAD

**Issue by rkrish108** [breser/git2consul#125]

**Comment by calvn** [comment]
What is the exact command that you are running, and can you also provide the config file?

**Comment by vigneshsenapathy** [comment]
@calvn  i am getting the same error

**Comment by breser** [comment]
I've seen this error when retrieving the config from consul via a key and you don't have permissions to retrieve it.  Unfortunately, I don't think there's enough info to really help here.  Since nobody has provided the full command as calvn asked for.  Going to close this.  Feel free to comment and we can reopen if there's more useful info.
