### ISSUE TITLE
git2consul causing defunct ssh processes

### ISSUE THREAD

**Issue by dustinbrown** [breser/git2consul#155]
Greetings,
I'm seeing an issue that i'm having a hard time debugging.  

I'm running git2consul in a docker container.  I'm launching git2consul as recommended `/usr/lib/node_modules/git2consul --config-file /etc/git2consul.d/config.json`. I do have a .ssh/config file so it can access our git server properly.
```
Host git.XXXXX.XXXX
  ProxyCommand ssh -i XXXXX -o StrictHostKeyChecking=no XXXX@XXXX.com nc %h %p
  IdentityFile /root/.ssh/XXX
  StrictHostKeyChecking no
```

 After polling git via ssh, git2consul is leaving processes in a zombie state.  Here is a sample:
```
root@5aff560343e7:/usr/lib/node_modules/git2consul# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 16:42 ?        00:00:00 /usr/bin/node /usr/lib/node_modules/git2consul --config-file /etc/git2consul.d/config.json
root        21     1  0 16:42 ?        00:00:00 [ssh] <defunct>
root        55     1  0 16:43 ?        00:00:00 [ssh] <defunct>
root        90     1  0 16:44 ?        00:00:00 [ssh] <defunct>
root       125     1  0 16:45 ?        00:00:00 [ssh] <defunct>
root       160     1  0 16:46 ?        00:00:00 [ssh] <defunct>
root       195     1  0 16:47 ?        00:00:00 [ssh] <defunct>
root       230     1  0 16:48 ?        00:00:00 [ssh] <defunct>
root       265     1  0 16:49 ?        00:00:00 [ssh] <defunct>
root       300     1  0 16:50 ?        00:00:00 [ssh] <defunct>
root       335     1  0 16:51 ?        00:00:00 [ssh] <defunct>
root       370     1  0 16:52 ?        00:00:00 [ssh] <defunct>
root       405     1  0 16:53 ?        00:00:00 [ssh] <defunct>
root       440     1  0 16:54 ?        00:00:00 [ssh] <defunct>
root       475     1  0 16:55 ?        00:00:00 [ssh] <defunct>
root       510     1  0 16:56 ?        00:00:00 [ssh] <defunct>
root       545     1  0 16:57 ?        00:00:00 [ssh] <defunct>
root       580     1  0 16:58 ?        00:00:00 [ssh] <defunct>
```

The only fix so far is reboot the docker container.  Any other debugging tips or suggestions?

**Comment by breser** [comment]
I'm guessing you're running git2consul as pid 1 inside your container.  But git2consul is not properly acting as the pid 1 process with respect to signal handling.  The Phusion folks wrote an excellent blog about this:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

How this relates to git2consul is that git2consul uses git, git runs ssh, git appears to exist without waiting for ssh to exist.  This orphans the ssh process, but since git2consul is not handling the child reaping you end up with the zombie ssh processes.

The Phusion folks in the blog previously mentioned wrote their own process to fill that role that is written in Python.  Unfortunately Python doesn't seem like a good idea to need to run a NodeJS app.  At my job we wrote our own C program for this purpose but I've never gotten around to cleaning it up for release.  Though I believe there are others around that serve the same purpose but I haven't used any so I'm not really comfortable recommending any.

**Comment by dustinbrown** [comment]
Thank you very much for the quick response.  Thanks for the information as well, very helpful!

**Comment by dustinbrown** [comment]
Ended up using https://github.com/krallin/tini to reap the child processes and it works great.
